default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  # - test
  # - analysis
  - release
  - deploy
  # - notification

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  # CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  # CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

  # Slack config
  IDENTIFICACAO_PROJETO: "*$CI_PROJECT_NAME $CI_COMMIT_REF_NAME*"
  SLACK_USERNAME: "DevOps - $CI_PROJECT_NAME $CI_COMMIT_REF_NAME"
  SLACK_CHANNEL: "#monitoramento"

1_build_project:
  stage: build
  script:
    - echo "Running build project..."
    - docker --version
    - docker compose version

    # - docker build
      # --pull
      # -build-arg USER=deployer
      # --build-arg UID=1000
      # --build-arg GID=1000
      # -f ./dockerfiles/php/Dockerfile
      # -t $CONTAINER_TEST_IMAGE .
    # - docker push $CONTAINER_TEST_IMAGE

    # fetches the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE:latest || true

    # builds the project, passing proxy variables, using OCI labels
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to
    # the GitLab registry
    - docker build
      --pull
      --build-arg USER=deployer
      --build-arg UID=1000
      --build-arg GID=1000
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# 2_unit_tests:
#   stage: test
#   dependencies:
#     - 1_build_project
#   script:
#     - echo "Running test project..."
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests

# 3_static_analysis:
#   stage: analysis
#   dependencies:
#     - 1_build_project
#   script:
#     - echo "Running Static Analysis..."
##     - ./vendor/bin/psalm --show-info=true
#     - php artisan insights --no-interaction --min-quality=80 --min-architecture=80 --min-style=80

4_release-image:
  stage: release
  dependencies:
    - 1_build_project
  script:
    # - docker pull $CONTAINER_TEST_IMAGE
    # - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    # - docker push $CONTAINER_RELEASE_IMAGE

    # Because we have no guarantee that this job will be picked up by the same runner
    # that built the image in the previous step, we pull it again locally
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Then we tag it "latest"
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    # Annnd we push it.
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

5_deploy_project:
  stage: deploy
  only:
    - main
  script:
    - echo "Running deploying project..."
    # - ./deploylalalalal.sh

# 6_success_notification:
#   stage: notification
#   when: on_success
#   only:
#     - main
#   variables:
#     SLACK_ICON: ':heavy_check_mark:'
#     NOTIFICATION_MESSAGE: "$SLACK_ICON Fim da atualização do $IDENTIFICACAO_PROJETO"
#     NOTIFY_NOW: 'curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\", \"username\": \"$SLACK_USERNAME\", \"text\": \"$NOTIFICATION_MESSAGE\"}" $SLACK_WEBHOOK_URL'
#   script:
#     - eval "$NOTIFY_NOW"

# 6_failure_notification:
#   stage: notification
#   when: on_failure
#   only:
#     - main
#   variables:
#     SLACK_ICON: ':heavy_check_mark:'
#     NOTIFICATION_MESSAGE: "$SLACK_ICON Falha no $IDENTIFICACAO_PROJETO"
#     NOTIFY_NOW: 'curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\", \"username\": \"$SLACK_USERNAME\", \"text\": \"$NOTIFICATION_MESSAGE\"}" $SLACK_WEBHOOK_URL'
#   script:
#     - eval "$NOTIFY_NOW"
