version: "3.9"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    image: store-ecommerce-v3-app
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
    depends_on:
      - db
      - redis
      - mailhog
    networks:
      - app-network

  supervisor:
    image: store-ecommerce-v3-app
    depends_on:
      - app
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    command: supervisord -c /etc/supervisor/conf.d/store-ecommerce.conf

  db:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-homestead}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      SERVICE_TAGS: ${SERVICE_TAGS:-dev}
      SERVICE_NAME: ${SERVICE_NAME:-db}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/config/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
      - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www
    entrypoint: ["npm"]
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redis:
    driver: "local"
